apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: greeter-gateway
  namespace: default
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
