apiVersion: v1
kind: Service
metadata:
  name: logoutput-svc
spec:
  type: ClusterIP
  selector:
    app: logoutput
  ports:
    - name: readstringport
      port: 2345
      protocol: TCP
      targetPort: 3000
    - name: pingpongport
      port: 2020
      protocol: TCP
      targetPort: 3003