apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: exercises
  name: logoutput-rollout
spec:
  replicas: 1
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: {duration: 1m}
        - analysis:
            templates:
            - templateName: cpu-usage-check
        - setWeight: 100
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: logoutput-configmap
      containers:
      - name: logoutput
        image: EXCERSISES/RANDOM_STRING
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /healthz
            port: 3004
        volumeMounts:
          - name: config-volume
            mountPath: /usr/app/information
            readOnly: true